### ISSUE TITLE
[DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.

### ISSUE THREAD

**Issue by tlunsfordCXP** [DataDog/datadog-ci#1283]
### Bug description

Running `datadog-ci git-metadata upload` returns the following error every time:

`[DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.`

This sort of warning makes it very difficult to maintain clean CI/CD pipelines. These warnings build up and eventually hide items that are real issues. ...which make this sort of issue a real issue.

The history of this repo shows the warning as occurring in this code for well over a year.

### Describe what you expected

No warning.

### Steps to reproduce the issue

`datadog-ci git-metadata upload`

### Additional context

Run in docker container `datadog/ci`.

### Command

git-metadata

**Comment by Drarig29** [comment]
Hi @tlunsfordCXP! What version of the Docker image are you using?

**Comment by tlunsfordCXP** [comment]
Latest.

**Comment by Drarig29** [comment]
Thanks for reporting!

The issue started in `datadog/ci:v2.25.0` because the Node.js version bundled in the Docker image went from `v20.8.1` to `v21.4.0`:

```bash
$ docker run --entrypoint node datadog/ci:v2.24.1 --version
v20.8.1

$ docker run --entrypoint node datadog/ci:v2.25.0 --version
v21.4.0
```

To reproduce the issue:
```bash
$ docker run -e NODE_OPTIONS=--trace-deprecation datadog/ci:v2.25.0 2>&1 | tail -n 14

You can also print more details about any of these commands by calling them with 
the `-h,--help` flag right after the command name.
(node:1) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
    at node:punycode:3:9
    at BuiltinModule.compileForInternalLoader (node:internal/bootstrap/realm:397:7)
    at BuiltinModule.compileForPublicLoader (node:internal/bootstrap/realm:333:10)
    at loadBuiltinModule (node:internal/modules/helpers:101:7)
    at Module._load (node:internal/modules/cjs/loader:1001:17)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@datadog/datadog-ci/node_modules/ent/encode.js:1:16)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
```

As you can see, the warning comes from [`ent`](https://www.npmjs.com/package/ent), which is a 9-years-old package to decode HTML entities.

It uses `punycode`, which used to be a native module in Node.js but [which is deprecated starting from Node 21](https://nodejs.org/api/punycode.html).

Since `ent` isn't maintained anymore, and the [corresponding repository was deleted](https://github.com/substack/node-ent), I'll make a PR on `@google-cloud/common` to use a different package.

**Comment by tlunsfordCXP** [comment]
Thank you!

**Comment by Drarig29** [comment]
Hi @tlunsfordCXP!

https://github.com/googleapis/nodejs-common/issues/812 was merged and released! 🎉 

But sadly, the warning still remains, and this time it's because of the `node-fetch` package, which is used by `gaxios` (used in multiple Google API packages).

This was already reported in https://github.com/googleapis/gaxios/issues/429#issuecomment-1833097220, and is tracked in https://github.com/googleapis/gaxios/issues/508.

We'll have to wait for `gaxios` to get rid of this warning. 🙇

**Comment by tlunsfordCXP** [comment]
Progress! Thank you!

Looks like that gaxios issue is fixed and awaiting their next release. 🤞

________________________________

**Comment by fishpen0** [comment]
It looks like this package still needs punycode via ajv

```
├─┬ @datadog/datadog-ci@2.46.2
│ └─┬ ajv@8.13.0
│   └─┬ uri-js@4.4.1
│     └── punycode@2.3.1
```

`ajv` 8.17.1 has removed punycode and datadog can now use it

**Comment by Drarig29** [comment]
Hi @fishpen0! The `ajv` package is only used by dev dependencies in datadog-ci, so it's not the culprit:

```sh
yarn why -R punycode
└─ @datadog/datadog-ci@workspace:.
   ├─ @microsoft/eslint-formatter-sarif@npm:3.1.0 (via npm:^3.0.0)
   │  └─ eslint@npm:8.57.0 (via npm:^8.9.0)
   │     ├─ @eslint/eslintrc@npm:2.1.4 (via npm:^2.1.4)
   │     │  └─ ajv@npm:6.12.6 (via npm:^6.12.4)
   │     │     └─ uri-js@npm:4.4.1 (via npm:^4.2.2)
   │     │        └─ punycode@npm:2.3.1 (via npm:^2.1.0)
   │     └─ ajv@npm:6.12.6 (via npm:^6.12.4)
   └─ eslint@npm:7.32.0 (via npm:^7.32.0)
      ├─ @eslint/eslintrc@npm:0.4.3 (via npm:^0.4.3)
      │  └─ ajv@npm:6.12.6 (via npm:^6.12.4)
      └─ ajv@npm:6.12.6 (via npm:^6.10.0)
```

We can still see the deprecation message in the latest version of datadog-ci:

```sh
$ docker run -e NODE_OPTIONS=--trace-deprecation datadog/ci:v2.46.2

(node:1) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
    at node:punycode:3:9
    at BuiltinModule.compileForInternalLoader (node:internal/bootstrap/realm:399:7)
    at BuiltinModule.compileForPublicLoader (node:internal/bootstrap/realm:338:10)
    at loadBuiltinModule (node:internal/modules/helpers:114:7)
    at Function._load (node:internal/modules/cjs/loader:1100:17)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:141:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/@datadog/datadog-ci/node_modules/whatwg-url/lib/url-state-machine.js:2:18)
```

And as I said above, this is caused by `whatwg-url`, which is a dependency of `node-fetch`:

```sh
yarn why -R whatwg-url
└─ @datadog/datadog-ci@workspace:.
   ├─ @google-cloud/logging@npm:11.1.0 (via npm:^11.1.0)
   │  ├─ @google-cloud/common@npm:5.0.2 (via npm:^5.0.0)
   │  │  ├─ google-auth-library@npm:9.7.0 (via npm:^9.0.0)
   │  │  │  ├─ gaxios@npm:6.7.0 (via npm:^6.1.1)
   │  │  │  │  └─ node-fetch@npm:2.7.0 [22a35] (via npm:^2.6.9 [22a35])
   │  │  │  │     └─ whatwg-url@npm:5.0.0 (via npm:^5.0.0)
   │  │  │  ├─ gcp-metadata@npm:6.1.0 (via npm:^6.1.0)
   │  │  │  │  └─ gaxios@npm:6.7.0 (via npm:^6.0.0)
   │  │  │  └─ gtoken@npm:7.1.0 (via npm:^7.0.0)
   │  │  │     └─ gaxios@npm:6.7.0 (via npm:^6.0.0)
   │  │  ├─ retry-request@npm:7.0.2 (via npm:^7.0.0)
   │  │  │  └─ teeny-request@npm:9.0.0 (via npm:^9.0.0)
   │  │  │     └─ node-fetch@npm:2.7.0 [22a35] (via npm:^2.6.9 [22a35])
   │  │  └─ teeny-request@npm:9.0.0 (via npm:^9.0.0)
   │  ├─ gcp-metadata@npm:6.1.0 (via npm:^6.0.0)
   │  ├─ google-auth-library@npm:9.7.0 (via npm:^9.0.0)
   │  └─ google-gax@npm:4.3.8 (via npm:^4.0.3)
   │     ├─ google-auth-library@npm:9.7.0 (via npm:^9.3.0)
   │     ├─ retry-request@npm:7.0.2 (via npm:^7.0.0)
   │     └─ node-fetch@npm:2.7.0 [22a35] (via npm:^2.6.9 [22a35])
   ├─ @google-cloud/run@npm:1.4.0 (via npm:^1.4.0)
   │  └─ google-gax@npm:4.3.8 (via npm:^4.0.3)
   ├─ google-auth-library@npm:9.12.0 (via npm:^9.12.0)
   │  ├─ gaxios@npm:6.7.0 (via npm:^6.1.1)
   │  ├─ gcp-metadata@npm:6.1.0 (via npm:^6.1.0)
   │  └─ gtoken@npm:7.1.0 (via npm:^7.0.0)
   └─ pkg@npm:5.8.1 [77038] (via npm:5.8.1 [77038])
      └─ pkg-fetch@npm:3.4.2 (via npm:3.4.2)
         └─ node-fetch@npm:2.7.0 [22a35] (via npm:^2.6.9 [22a35])
```

This may have been fixed since my last message though, so I'll look into a possible update.

**Comment by jakub-g** [comment]
I did some digging:


FWIW: 
- Current version of whatwg-url is `14.x`
- The punycode dep was removed in `whatwg-url@9.x` [(release logs)](https://github.com/jsdom/whatwg-url/releases/tag/v9.0.0)
- From reading whatwg-url release notes, pretty much every breaking release is mostly about raising minimum supported nodejs version

In theory, this dep from node-fetch to whatwg-url is a de facto noop since nodejs 7.x because [node 7.x shipped the URL module](https://nodejs.org/api/url.html#class-url), and node-fetch@2 uses whatwg-url as follows: `const URL = Url.URL || whatwgUrl.URL;`
- https://github.com/node-fetch/node-fetch/blob/2.x/src/index.js#L23-L25
- https://github.com/node-fetch/node-fetch/blob/2.x/src/request.js#L12-L17

Although, I just tried forcing whatwg-url@14 through yarn resolution in my userland repo, and I get `ReferenceError: TextEncoder is not defined` [here](https://github.com/jsdom/whatwg-url/blob/main/lib/encoding.js#L2) which makes no sense with node22 🤔

**Comment by jakub-g** [comment]
FWIW, until this is fixed, it's possible to suppress this warning by running datadog-ci as follows:

```
NODE_OPTIONS='--disable-warning=DEP0040' yarn datadog-ci ... 
```

**Comment by Drarig29** [comment]
Note that there is some update on `google-auth-library`'s side: https://github.com/googleapis/google-auth-library-nodejs/pull/1938 was created, and updates `gaxios` to `7.0.0-rc.1`, which includes https://github.com/googleapis/gaxios/pull/617.

**Comment by Drarig29** [comment]
> Maybe the remaining non-migrated usages are not called from our code paths.

@jakub-g the issue is that we currently import all commands at startup, which import all the dependencies. And the `punycode` deprecation warning happens at import time.

I'll try with some `await import()` at the right places.
